services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab15
    
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: springboot
    build:
      context: ./backend-springbootapp-31371
      dockerfile: backend.Dockerfile
    ports:
      - "1977:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./frontend-reactapp-31371
      dockerfile: frontend.Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: